//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package internal

import (
	_ "embed"
)

//go:embed schemas/FileCleanupOutput.schema.json
var schemaFileCleanupOutput []byte

//go:embed schemas/FileCleanupSpec.schema.json
var schemaFileCleanupSpec []byte

//go:embed schemas/FileCleanupTransformation.schema.json
var schemaFileCleanupTransformation []byte

//go:embed schemas/SignOCIArtifactOutput.schema.json
var schemaSignOCIArtifactOutput []byte

//go:embed schemas/SignOCIArtifactSpec.schema.json
var schemaSignOCIArtifactSpec []byte

//go:embed schemas/SignOCIArtifactTransformation.schema.json
var schemaSignOCIArtifactTransformation []byte

// JSONSchema returns the JSON Schema for FileCleanupOutput.
func (FileCleanupOutput) JSONSchema() []byte {
	return schemaFileCleanupOutput
}

// JSONSchema returns the JSON Schema for FileCleanupSpec.
func (FileCleanupSpec) JSONSchema() []byte {
	return schemaFileCleanupSpec
}

// JSONSchema returns the JSON Schema for FileCleanupTransformation.
func (FileCleanupTransformation) JSONSchema() []byte {
	return schemaFileCleanupTransformation
}

// JSONSchema returns the JSON Schema for SignOCIArtifactOutput.
func (SignOCIArtifactOutput) JSONSchema() []byte {
	return schemaSignOCIArtifactOutput
}

// JSONSchema returns the JSON Schema for SignOCIArtifactSpec.
func (SignOCIArtifactSpec) JSONSchema() []byte {
	return schemaSignOCIArtifactSpec
}

// JSONSchema returns the JSON Schema for SignOCIArtifactTransformation.
func (SignOCIArtifactTransformation) JSONSchema() []byte {
	return schemaSignOCIArtifactTransformation
}
